### ISSUE TITLE
Adequação de campos base existentes no projeto para permissão de valores anuláveis

### ISSUE THREAD

**Issue by jonathanperis** [peris-studio/loja-do-valdir#10]
Eu como:

- Administrador

Quero:

- Que seja feita uma adequação na estrutura das classes `Cliente` e `Endereco`

De modo que:

- Os campos a seguir passem a ser **anuláveis**

- - DataAtualizacao (DateTime)
- - DataDelecao (DateTime)
- - Ativo (bool)

Critérios de aceite:

- Os campos mencionados devem passar a ser anuláveis
- Verifique [este link](https://learn.microsoft.com/pt-br/dotnet/csharp/language-reference/builtin-types/nullable-value-types) para entender como tornar propriedades anuláveis no C#
- O proposito de tornar os campos mencionados anuláveis, é que não estamos passando valores para eles no momento da criação deles. Então por não terem um valor no ato inicial da classe, eles podem ser anuláveis (valor nulo) até que tenham um valor.
- Esta branch deverá ser uma branch de `chore`

**Comment by Hisllaylla** [comment]
A pasta se mantém feat?

**Comment by jonathanperis** [comment]
> A pasta se mantêm feat?

Não. A pasta deverá ser `chore`
