### ISSUE TITLE
Criação do método Inserir para carregar um novo endereço utilizando o modelo

### ISSUE THREAD

**Issue by jonathanperis** [peris-studio/loja-do-valdir#11]
Eu como:

- Administrador

Quero:

- Que seja criado um novo método na classe `Endereco` chamado `Inserir`

De modo que:

- Este método receba por parametro os seguintes argumentos:
- - logradouro (string)
- - numero (string)
- - bairro (string)
- - cidade (string)
- - UF (string)

- Este método deverá ter um retorno do tipo `Endereco`
- Este método deverá criar uma nova instancia de `Endereco`com os parametros informados
- O Campo `DataCriacao` deverá ter um valor da data do momento da criação do objeto (verifique [este link](https://stackoverflow.com/questions/69798302/datetime-now-equivalent-for-timeonly-and-dateonly) para entender como fazer)
- O campo `Ativo`deverá ter o valor `true`

Critérios de aceite:

- A criação do método de acordo com os parametros acima informados
- Dica: Caso você não saiba o que estiver fazendo, nesta task e em qualquer outra task subsequente, o ChatGPT poderá ser o seu copiloto para te auxiliar nas tarefas. Desde que você forneça comentários a respeito do que está acontecendo no codigo, isto não é um problema.
- O método não precisa ser testado neste momento, apenas criado.
- O método deverá ter o modificador de acesso `public`

**Comment by Hisllaylla** [comment]
A principio, a propriedade ```public int Numero { get; set; }``` é do tipo ```int```, e nesse método, se pede do tipo ```string```. Altera a propriedade da classe ou o método?
