### ISSUE TITLE
Corrigir a alocação da pasta Models no projeto

### ISSUE THREAD

**Issue by jonathanperis** [peris-studio/loja-do-valdir#16]
Eu como:

- Administrador

Quero:

- Que seja arrumada a localidade da pasta `Models`

De modo que:

- A pasta `Models` fique a locada dentro da pasta `src/LojaDoValdir`

Critérios de aceite:

- A pasta `Models` e todo o seu conteúdo deverá estar alocado fisicamente dentro da pasta `src/LojaDoValdir`
- O nome da branch deverá ter o prefixo `fix`

**Comment by Hisllaylla** [comment]
A correção fez com que a issue #8 houvesse problema. Foi pedido que a data de criação anteriormente ```DateTime``` na classe ```Cliente```, fosse posta no método ```Inserir```, ainda da classe ```Cliente```. A issue pede para que mude e se torne ```OnlyData``` somente no método, sendo que a propriedade do cliente é ```DateTime```. Foi linkado uma página do stackoverflow para entender a conversão, porém ainda assim, houve erro. Corrigi para ```DateTime.Now```, entrando nos conformes, porém vai contra a issue anterior. O que fazer?
