### ISSUE TITLE
Criação do modelo de Item de Pedido

### ISSUE THREAD

**Issue by jonathanperis** [peris-studio/loja-do-valdir#28]
Eu como:

- Administrador

Gostaria de:

- Que fosse criado um modelo de **PedidoItem** no sistema

De modo que:

- Este modelo contenha as seguintes propriedades:
  - Id (guid)
  - Preco (double)
  - DataCriação (DateTime)
  - DataAtualização (DateTime)
  - DataDelecao (DateTime)
  - Ativo (bool)
  - PedidoId (guid)
  - Pedido (objeto)
  - ItemId (guid)
  - Item (objeto)

- Este modelo de deve ter um método chamado `Inserir` que receberá por parametro os seguintes argumentos:
   - Preco (double)
   - PedidoId (guid)
   - ItemId (guid)

- Este método deverá ter um retorno do tipo `PedidoItem`
- Este método deverá criar uma nova instancia de `PedidoItem`com os parametros informados
- O Campo `DataCriacao` deverá ter um valor da data do momento da criação do objeto (verifique [este link](https://stackoverflow.com/questions/69798302/datetime-now-equivalent-for-timeonly-and-dateonly) para entender como fazer)
- O campo `Ativo`deverá ter o valor `true`

- Este modelo deve ter um método chamado `Atualizar` que receberá por parametro os seguintes argumentos:
   - PedidoItem (objeto PedidoItem)
   - Preco (double)

- Este método deverá ter um retorno do tipo `PedidoItem`
- Este método deverá modificar os valores do argumento Usuario, com os valores que foram informados nos argumentos posteriores
- O campo DataCriacao não poderá ser atualizado neste método
- O campo Ativo não poderá ser atualizado neste método
- O Campo `DataAtualizacao` deverá ter um valor da data do momento da criação do objeto (verifique [este link](https://stackoverflow.com/questions/69798302/datetime-now-equivalent-for-timeonly-and-dateonly) para entender como fazer)

- Este modelo de deve ter um método chamado `Remover` que receberá por parametro os seguintes argumentos:
   - PedidoItem (objeto PedidoItem)

- Este método deverá ter um retorno do tipo `PedidoItem`
- O Campo `DataDelecao` deverá ter um valor da data do momento da criação do objeto (verifique [este link](https://stackoverflow.com/questions/69798302/datetime-now-equivalent-for-timeonly-and-dateonly) para entender como fazer)
- O campo Ativo deverá ter um valor `false`

Critérios de aceite:

- Deverá ser criada uma `class` de nome `PedidoItem`. Esta class deverá ficar em uma pasta chamada `Models`
- As propriedades criadas deverão ter o sufixo `{ get; set; }`
- As propriedades deverão ter o modificador de acesso `public`
- A classe deverá ter o modificador de acesso `public`

- A criação do método de acordo com os parametros acima informados
- Dica: Caso você não saiba o que estiver fazendo, nesta task e em qualquer outra task subsequente, o ChatGPT poderá ser o seu copiloto para te auxiliar nas tarefas. Desde que você forneça comentários a respeito do que está acontecendo no codigo, isto não é um problema.
- O método não precisa ser testado neste momento, apenas criado.
- O método deverá ter o modificador de acesso `public`

**Comment by Hisllaylla** [comment]
> Este método deverá modificar os valores do argumento Usuario, com os valores que foram informados nos argumentos posteriores

Não deveria ser do argumento `PedidoItem`?

**Comment by jonathanperis** [comment]
> > Este método deverá modificar os valores do argumento Usuario, com os valores que foram informados nos argumentos posteriores
> 
> Não deveria ser do argumento `PedidoItem`?
> 

Correto.
